version: "3.4"

services:
  db:
    platform: linux/amd64
    image: postgres:14.0
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fastserver
      POSTGRES_USER: fastserver
      POSTGRES_PASSWORD: fastserver
    ports:
      - 5432:5432
    restart: always
  webserver:
    platform: linux/amd64
    image: fastserver
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://fastserver:fastserver@db:5432/fastserver
      - PORT=4000
      - HOST=0.0.0.0
    ports:
      - 4000:4000
    depends_on:
      - db
